### ISSUE TITLE
Error at starting

### ISSUE THREAD

**Issue by Oberonskii** [google/making_with_ml#52]
So I followed every step.But when i run it, it says:

Error [TOKEN_INVALID]: An invalid token was provided.
    at Client.login (/home/pi/Desktop/Discord/discord_moderator/node_modules/discord.js/src/client/Client.js:206:52)
    at Object.<anonymous> (/home/pi/Desktop/Discord/discord_moderator/discord.js:141:8)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  [Symbol(code)]: 'TOKEN_INVALID'

but the API key and the Bot Token are the right. Could someone help please?

**Comment by Oberonskii** [comment]
And its also the smae on my Windows computer

**Comment by Oberonskii** [comment]
And it also says the same on my Windows computer

**Comment by Oberonskii** [comment]
I got it working. Changed the code
